import { useEffect, useMemo, useState } from "react";
import { getStudentLoginCredentialsForAdmin } from "../../services/adminService";

function formatDateTime(value) {
  if (!value) return "-";

  return new Date(value).toLocaleString("en-NG", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function AdminLoginCredentials() {
  const [credentials, setCredentials] = useState([]);
  const [search, setSearch] = useState("");
  const [notice, setNotice] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  async function loadCredentials() {
    setIsLoading(true);
    setErrorMessage("");

    const { data, error } = await getStudentLoginCredentialsForAdmin();

    if (error) {
      setErrorMessage(error.message || "Could not load credentials.");
      setIsLoading(false);
      return;
    }

    setCredentials(data || []);
    setIsLoading(false);
  }

  useEffect(() => {
    loadCredentials();
  }, []);

  const filteredCredentials = useMemo(() => {
    const term = search.trim().toLowerCase();

    if (!term) return credentials;

    return credentials.filter((credential) => {
      return (
        String(credential.student_name || "").toLowerCase().includes(term) ||
        String(credential.email || "").toLowerCase().includes(term)
      );
    });
  }, [credentials, search]);

  async function copyCredential(credential) {
    const text = `Jlux Academy Student Login Details

Student Name: ${credential.student_name || "-"}
Email: ${credential.email || "-"}
Temporary Password: ${credential.temporary_password || "-"}
Login Link: ${credential.login_url || "https://jluxacademy.vercel.app/login"}

Please change your password after logging in.`;

    try {
      await navigator.clipboard.writeText(text);
      setNotice(`Login details copied for ${credential.student_name || credential.email}.`);
    } catch {
      setErrorMessage("Could not copy automatically. Please copy manually.");
    }
  }

  return (
    <>
      <header className="dashboardHeader">
        <div>
          <p className="eyebrow">Admin Login Access</p>
          <h1>Student Login Credentials</h1>
          <p>
            View student login credentials generated during approval. These are
            the temporary passwords created by the system.
          </p>
        </div>

        <button type="button" onClick={loadCredentials}>
          Refresh
        </button>
      </header>

      {notice && <div className="successNotice">{notice}</div>}
      {errorMessage && <div className="errorNotice">{errorMessage}</div>}

      <section className="dashboardPanel">
        <div className="panelHeaderRow">
          <div>
            <h2>Credentials List</h2>
            <p>
              If a student changes their password later, this page will still
              show the last temporary password generated by admin approval.
            </p>
          </div>

          <input
            type="search"
            placeholder="Search name or email..."
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            style={{
              width: "260px",
              maxWidth: "100%",
              padding: "12px 14px",
              borderRadius: "12px",
              border: "1px solid #d5dce8",
            }}
          />
        </div>

        {isLoading ? (
          <p>Loading credentials...</p>
        ) : filteredCredentials.length === 0 ? (
          <p>No student credentials found yet.</p>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Student</th>
                <th>Email</th>
                <th>Temporary Password</th>
                <th>Status</th>
                <th>Generated</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {filteredCredentials.map((credential) => (
                <tr key={credential.id}>
                  <td>{credential.student_name || "-"}</td>
                  <td>{credential.email || "-"}</td>
                  <td>
                    <strong style={{ color: "#0b4ea2" }}>
                      {credential.temporary_password || "-"}
                    </strong>
                  </td>
                  <td>{credential.password_status || "-"}</td>
                  <td>{formatDateTime(credential.generated_at)}</td>
                  <td>
                    <button
                      type="button"
                      className="tableActionBtn restoreBtn"
                      onClick={() => copyCredential(credential)}
                    >
                      Copy
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </>
  );
}

export default AdminLoginCredentials;